<?php
require __DIR__.'/includes/bootstrap.php';
header('Content-Type: application/json; charset=utf-8');
if(!$user){http_response_code(401);echo json_encode(['error'=>'Sign in to continue.']);exit;}
try{
 $action=$_GET['action']??'calendar';
 if($action==='calendar'){
  $events=[];foreach(requests() as $r){if(in_array($r['status'],['Draft','Returned for Correction']))continue;$events[]=['id'=>$r['id'],'reference'=>$r['reference'],'title'=>$r['destination'],'purpose'=>$r['purpose'],'start'=>$r['start_datetime'],'end'=>$r['end_datetime'],'status'=>$r['status'],'vehicle_id'=>$r['vehicle_id'],'vehicle'=>$r['model']??'Awaiting assignment','plate'=>$r['plate']??'—','type'=>$r['vehicle_type'],'office_id'=>$r['office_id'],'office'=>$r['office_name'],'office_code'=>$r['office_code'],'requester'=>$r['requester_name'],'driver_id'=>$r['driver_id'],'driver'=>$r['driver_name']??'Awaiting assignment'];}
  foreach(all('SELECT b.*,v.model,v.plate,v.type FROM vehicle_blocks b JOIN vehicles v ON v.id=b.vehicle_id') as $b)$events[]=['id'=>'block-'.$b['id'],'title'=>$b['reason'],'start'=>$b['start_datetime'],'end'=>$b['end_datetime'],'status'=>'Maintenance','vehicle_id'=>$b['vehicle_id'],'vehicle'=>$b['model'],'plate'=>$b['plate'],'type'=>$b['type'],'office_id'=>'','office'=>'Fleet maintenance','office_code'=>'GSO','requester'=>'','driver_id'=>'','driver'=>'—'];
  echo json_encode(['events'=>$events,'vehicles'=>all('SELECT id,model,plate,type FROM vehicles ORDER BY model')],JSON_THROW_ON_ERROR);
 }elseif($action==='availability'){
  require_role('Administrator','Administrative Officer');$r=get_request((int)($_GET['id']??0));$vehicle=(int)($_GET['vehicle_id']??0);$driver=(int)($_GET['driver_id']??0);$v=one('SELECT * FROM vehicles WHERE id=?',[$vehicle]);$d=one('SELECT * FROM drivers WHERE id=?',[$driver]);if(!$v||!$d)throw new RuntimeException('Select a vehicle and a driver first.');$issues=conflicts($vehicle,$driver,$r['start_datetime'],$r['end_datetime'],$r['id']);if(!in_array($v['status'],['Available','Reserved']))$issues[]='Vehicle is '.$v['status'].'.';if($d['status']!=='Available')$issues[]='Driver is unavailable.';if($d['license_expiry']<substr($r['end_datetime'],0,10))$issues[]='Driver license expires before return.';if($v['registration_expiry']<substr($r['end_datetime'],0,10))$issues[]='Vehicle registration expires before return.';if(count(array_filter(preg_split('/[,\n]+/',$r['passengers'])))>$v['capacity'])$issues[]='Passenger count exceeds capacity.';echo json_encode(['available'=>!$issues,'message'=>$issues?implode(' ',$issues):'Vehicle and driver are available, including the '.setting('turnaround_minutes').' minute turnaround buffer.']);
 }else{http_response_code(404);echo json_encode(['error'=>'Unknown endpoint.']);}
}catch(Throwable $e){http_response_code(400);echo json_encode(['error'=>$e instanceof PDOException?'Unable to load records.':$e->getMessage()]);}
