<?php
require __DIR__.'/includes/bootstrap.php';
if($user)redirect('index.php');$error='';
if($_SERVER['REQUEST_METHOD']==='POST')try{
 check_csrf();$email=strtolower(field('email',190));$identity=hash('sha256',($_SERVER['REMOTE_ADDR']??'local').'|'.$email);$since=date('Y-m-d H:i:s',time()-900);
 if((int)one('SELECT COUNT(*) n FROM login_attempts WHERE identity_hash=? AND attempted_at>?',[$identity,$since])['n']>=5)throw new RuntimeException('Too many attempts. Try again in 15 minutes.');
 run('INSERT INTO login_attempts(identity_hash,attempted_at) VALUES(?,?)',[$identity,date('Y-m-d H:i:s')]);
 $account=one("SELECT * FROM users WHERE email=? AND status='Active'",[$email]);
 if(!$account||!password_verify((string)($_POST['password']??''),$account['password_hash']))throw new RuntimeException('Email or password is incorrect.');
 session_regenerate_id(true);$_SESSION['user_id']=$account['id'];$_SESSION['csrf']=bin2hex(random_bytes(32));$user=$account;run('DELETE FROM login_attempts WHERE identity_hash=?',[$identity]);audit('Signed in');redirect('index.php');
}catch(Throwable $e){$error=$e instanceof PDOException?'Sign in is temporarily unavailable.':$e->getMessage();}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sign in · VRS</title><link rel="stylesheet" href="assets/css/style.css"></head><body class="login-body"><main class="login-layout"><section class="login-brand"><a class="brand" href="index.php"><span class="brand-icon"><?=icon('car',27)?></span><span>VRS<span class="brand-sub">FLEET OPERATIONS</span></span></a><div><span class="eyebrow">A BETTER WAY TO MOVE</span><h1>Every journey.<br>Working together.</h1><p>A connected workspace for your vehicle requests, fleet schedules, and official trips.</p><div class="route-art"><span class="route-dot"></span><div class="route-line"></div><span class="route-car"><?=icon('car',42)?></span><div class="route-line"></div><span class="route-dot end"></span></div></div><small>Vehicle Requisition & Scheduling System</small></section><section class="login-form"><div><span class="eyebrow">WELCOME BACK</span><h2>Sign in to your workspace</h2><p class="muted">Keep your people and your fleet moving.</p><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif?><form method="post" class="stack"><?=csrf()?><label>Email address<input name="email" type="email" required autocomplete="username" value="<?=e($_POST['email']??'')?>" placeholder="you@your-office.gov.ph"></label><label>Password<input name="password" type="password" required autocomplete="current-password" placeholder="Enter your password"></label><button class="btn primary" type="submit">Sign in <?=icon('arrow',17)?></button></form><?php if($config['demo']):?><div class="demo-card"><strong>Explore the demo workspace</strong><p>Sample data · local SQLite database</p><form method="post"><?=csrf()?><input type="hidden" name="email" value="daniel@vrs.local"><input type="hidden" name="password" value="Demo@12345"><button class="btn" type="submit">Enter as administrator <?=icon('arrow',16)?></button></form><small>Other roles: requester, supervisor, admin, or dispatch<br>@vrs.local · Password: Demo@12345</small><p style="margin-top:14px"><a class="text-link" href="setup.php">Install a MySQL workspace →</a></p></div><?php endif?></div></section></main></body></html>
