<?php
require __DIR__.'/../includes/bootstrap.php';if(!$user)redirect('../login.php');
try{
 $r=personnel_booking(record_link_id($_GET['id']??'','personnel-print:id'));
 if(!in_array($r['status'],['Approved','In Progress','Completed']))throw new RuntimeException('Only approved personnel requisitions can be printed.');
 $approval=one("SELECT h.*,u.full_name FROM personnel_booking_history h JOIN users u ON u.id=h.user_id WHERE h.booking_id=? AND h.decision='Approved' ORDER BY h.id DESC",[$r['id']]);
}catch(RuntimeException $e){http_response_code(403);exit(e($e->getMessage()));}
$staff=$r['assigned_personnel'];
if(!$staff&&!empty($r['personnel_name']))$staff=[['full_name'=>$r['personnel_name'],'position'=>$r['personnel_position'],'classification'=>'','employee_number'=>'']];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?=e($r['reference'])?> · Personnel requisition</title>
<link rel="stylesheet" href="../assets/css/personnel-slip.css?v=<?=filemtime(__DIR__.'/../assets/css/personnel-slip.css')?>">
</head><body>
<nav class="print-toolbar" aria-label="Slip actions"><a href="<?=e(secure_record_url('../index.php?page=personnel-request&id='.$r['id']))?>">← Back to requisition</a><button type="button" onclick="window.print()">Print / Save as PDF</button></nav>
<main class="personnel-slip">
<header class="slip-header"><div class="organization"><span class="brand-mark" aria-hidden="true">VRS</span><div><p class="eyebrow">OFFICIAL PERSONNEL ASSIGNMENT</p><p class="organization-name"><?=e(setting('organization'))?></p></div></div><div class="document-title"><div><h1>PERSONNEL REQUISITION</h1><p>Authorization for an official staff assignment</p></div><div class="reference"><span class="field-label">REQUISITION NO.</span><strong><?=e($r['reference'])?></strong><span class="status"><?=e($r['status'])?></span></div></div></header>
<section class="request-summary" aria-label="Requesting office"><div><span class="field-label">REQUESTED BY</span><strong><?=e($r['requester_name'])?></strong></div><div><span class="field-label">OFFICE / DIVISION</span><strong><?=e($r['office_name'])?></strong></div><div><span class="field-label">DATE REQUESTED</span><strong><?=shortdate($r['created_at'],'M j, Y')?></strong></div></section>
<section class="slip-section"><h2><span>01</span> Assignment details</h2><div class="schedule"><div><span class="field-label">START OF ASSIGNMENT</span><strong><?=shortdate($r['start_datetime'],'M j, Y')?></strong><span><?=shortdate($r['start_datetime'],'g:i A')?></span></div><div><span class="field-label">END OF ASSIGNMENT</span><strong><?=shortdate($r['end_datetime'],'M j, Y')?></strong><span><?=shortdate($r['end_datetime'],'g:i A')?></span></div></div><dl class="assignment-details"><div><dt>Location / destination</dt><dd><?=nl2br(e($r['destination']))?></dd></div><div><dt>Required position / specialty</dt><dd><?=e($r['requested_role'])?></dd></div><div><dt>Preferred personnel</dt><dd><?=e($r['preferred_personnel']?:'No preference indicated')?></dd></div><div class="purpose"><dt>Purpose / duties</dt><dd><?=nl2br(e($r['purpose']))?></dd></div></dl></section>
<section class="slip-section"><h2><span>02</span> Assigned personnel <small><?=count($staff)?> <?=count($staff)===1?'person':'people'?></small></h2><table class="personnel-table"><caption class="sr-only">Personnel authorized for this assignment</caption><thead><tr><th scope="col" class="number-column">NO.</th><th scope="col">NAME / EMPLOYEE NO.</th><th scope="col">CLASSIFICATION</th><th scope="col">POSITION / SPECIALTY</th></tr></thead><tbody><?php foreach($staff as $i=>$person):?><tr><td class="row-number"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></td><td><strong><?=e($person['full_name'])?></strong><?php if(!empty($person['employee_number'])):?><small><?=e($person['employee_number'])?></small><?php endif?></td><td><?=e($person['classification']?:'—')?></td><td><?=e($person['position']?:'—')?></td></tr><?php endforeach?></tbody></table></section>
<section class="slip-section approval-section"><h2><span>03</span> Authorization</h2><div class="approval-record"><span class="field-label">APPROVAL RECORDED</span><p><?=!empty($approval['created_at'])?shortdate($approval['created_at'],'M j, Y · g:i A'):'—'?></p></div><?php if(!empty($approval['remarks'])):?><div class="approval-remarks"><span class="field-label">APPROVAL REMARKS</span><p><?=nl2br(e($approval['remarks']))?></p></div><?php endif?><div class="signatures"><div><span class="field-label">REQUESTED BY</span><div class="signature-line"></div><strong><?=e($r['requester_name'])?></strong><small>Signature over printed name</small></div><div><span class="field-label">APPROVED BY</span><div class="signature-line"></div><strong><?=e($approval['full_name']??'')?></strong><small>Administrator · Signature over printed name</small></div></div></section>
<?php if(!empty($r['actual_start'])||!empty($r['actual_end'])):?><section class="completion-record"><h2>Assignment record</h2><div><span>Actual start <strong><?=!empty($r['actual_start'])?shortdate($r['actual_start'],'M j, Y · g:i A'):'—'?></strong></span><span>Actual completion <strong><?=!empty($r['actual_end'])?shortdate($r['actual_end'],'M j, Y · g:i A'):'—'?></strong></span></div></section><?php endif?>
<footer class="slip-footer"><span><strong><?=e($r['reference'])?></strong> · Personnel requisition</span><span>Printed by <?=e($user['full_name'])?><br><?=date('M j, Y · g:i A')?></span></footer>
</main></body></html>
