<?php
$rows=requests();$today=date('Y-m-d');$now=date('Y-m-d H:i:s');
$todayTrips=array_values(array_filter(calendar_requests(),fn($r)=>substr($r['start_datetime'],0,10)<=$today&&substr($r['end_datetime'],0,10)>=$today&&!in_array($r['status'],['Cancelled','Rejected','Draft','Returned for Correction'])));
usort($todayTrips,fn($a,$b)=>strcmp($a['start_datetime'],$b['start_datetime']));
$fleet=all('SELECT * FROM vehicles ORDER BY id');$active=all("SELECT * FROM requisitions WHERE status='Dispatched'");$activeIds=array_column($active,'vehicle_id');
$blocked=array_column(all('SELECT vehicle_id FROM vehicle_blocks WHERE start_datetime<=? AND end_datetime>?',[$now,$now]),'vehicle_id');
$reservedIds=array_column(all("SELECT vehicle_id FROM requisitions WHERE status='Approved' AND start_datetime<=? AND end_datetime>?",[$now,$now]),'vehicle_id');
$available=count(array_filter($fleet,fn($v)=>$v['status']==='Available'&&!in_array($v['id'],$activeIds)&&!in_array($v['id'],$blocked)&&!in_array($v['id'],$reservedIds)));
$pending=array_values(array_filter($rows,fn($r)=>in_array($r['status'],['Pending Supervisor','Pending Administrative Approval'])));
$maintenance=count(array_filter($fleet,fn($v)=>$v['status']==='Under Maintenance'||in_array($v['id'],$blocked)));
$completed=count(array_filter($rows,fn($r)=>in_array($r['status'],['Returned','Completed'])));
$overdue=count(array_filter($active,fn($r)=>$r['end_datetime']<$now));
page_heading('Overview','A clear view of your fleet. A smooth start to every journey.',new_button());
?><section class="welcome-banner"><div><span class="eyebrow">YOUR FLEET, IN FOCUS</span><h2>Good <?=date('G')<12?'morning':(date('G')<18?'afternoon':'evening')?>, <?=e(explode(' ',$user['full_name'])[0])?> <span class="greeting-sun">☀</span></h2><p><?=is_role('Administrator')?'There are':'You have'?> <strong><?=count($todayTrips)?> scheduled trips</strong> today. Let’s keep things moving.</p><a href="index.php?page=calendar&view=day&date=<?=$today?>">View today’s schedule <?=icon('arrow',16)?></a></div><div class="banner-art" aria-hidden="true"><div class="road road-one"></div><div class="road road-two"></div><div class="art-circle"></div><div class="art-car"><?=icon('car',66)?></div><div class="art-location"><span></span></div><div class="art-label"><i></i> Ready for the road</div></div></section>
<section class="stat-grid" aria-label="Fleet statistics"><?php foreach([
 ['Available vehicles',$available,'of '.count($fleet).' vehicles in your fleet','car','green','vehicles'],['Vehicles in use',count($active),'On the road right now','arrow','blue','dispatch'],['Scheduled trips',count($todayTrips),'For today, '.date('F j'),'calendar','purple','calendar'],['Pending approvals',count($pending),'Requests awaiting review','clock','amber',is_role('Administrator')?'approvals':'requisitions']
] as [$label,$count,$sub,$ico,$color,$link]):?><div class="stat-card"><div class="stat-top"><span><?=$label?></span><span class="stat-icon <?=$color?>"><?=icon($ico,20)?></span></div><strong class="stat-number"><?=$count?><span class="stat-dash">—</span></strong><small><?=$sub?></small></div><?php endforeach?></section>
<div class="dashboard-grid"><section class="panel schedule-panel"><div class="panel-heading"><div><h2><?=is_role('Administrator')?'Today’s fleet schedule':'Your schedule today'?> <span class="count-pill"><?=count($todayTrips)?></span></h2><p><?=date('l, F j, Y')?></p></div><a class="text-link" href="index.php?page=calendar&view=day">View calendar <?=icon('arrow',15)?></a></div><div class="trip-list"><?php foreach(array_slice($todayTrips,0,4) as $r):?><a class="trip-item" href="index.php?page=request&id=<?=$r['id']?>"><div class="trip-time"><strong><?=shortdate($r['start_datetime'],'g:i')?><small><?=shortdate($r['start_datetime'],'A')?></small></strong><span><?=shortdate($r['end_datetime'],'g:i A')?></span></div><div class="trip-marker <?= $r['status']==='Dispatched'?'purple':'blue'?>"></div><div class="trip-info"><h3><?=e($r['destination'])?></h3><p><?=e($r['purpose'])?></p><div class="trip-meta"><span><?=icon('car',14)?> <?=e($r['model']??'Unassigned')?> <b>·</b> <?=e($r['plate']??'—')?></span><span><?=icon('office',14)?> <?=e($r['office_code'])?></span></div></div><div class="trip-status"><?=badge($r['status'])?><?=icon('chevron',16)?></div></a><?php endforeach;if(!$todayTrips):?><div class="empty-state"><?=icon('calendar',30)?><h3>A clear schedule</h3><p>No trips are scheduled for today.</p></div><?php endif?></div><a class="panel-bottom" href="index.php?page=calendar&view=day">See full daily schedule <?=icon('arrow',15)?></a></section>
<section class="panel fleet-panel"><div class="panel-heading"><div><h2>Fleet at a glance</h2><p>Current vehicle availability</p></div><span class="live-pill"><i></i> LIVE</span></div><div class="fleet-donut" style="--available:<?=count($fleet)?round($available/count($fleet)*100):0?>%;--active:<?=count($fleet)?round(($available+count($active))/count($fleet)*100):0?>%;--maintenance:<?=count($fleet)?round(($available+count($active)+$maintenance)/count($fleet)*100):0?>%"><div><strong><?=count($fleet)?></strong><span>Total vehicles</span></div></div><div class="fleet-legend"><div><span><i class="legend-dot green"></i>Available</span><strong><?=$available?></strong></div><div><span><i class="legend-dot blue"></i>In use</span><strong><?=count($active)?></strong></div><div><span><i class="legend-dot amber"></i>Maintenance</span><strong><?=$maintenance?></strong></div><div><span><i class="legend-dot gray"></i>Other / reserved</span><strong><?=max(0,count($fleet)-$available-count($active)-$maintenance)?></strong></div></div><?php if(manage()):?><a class="panel-bottom" href="index.php?page=vehicles">Manage fleet <?=icon('arrow',15)?></a><?php endif?></section></div>
<section class="panel recent-panel"><div class="panel-heading"><div><h2>Recent requisitions</h2><p>The latest requests across your workspace</p></div><a class="text-link" href="index.php?page=requisitions">View all requisitions <?=icon('arrow',15)?></a></div><?php $recent=$rows;usort($recent,fn($a,$b)=>$b['id']<=>$a['id']);request_table(array_slice($recent,0,5),true);?></section>
<div class="bottom-insights"><div><?=icon('check',20)?><span><strong><?=$completed?> trips returned</strong> in your visible records</span></div><div><?=icon('wrench',20)?><span><strong><?=$maintenance?> vehicles in maintenance</strong> keeping your fleet road-ready</span></div><div><?=icon('clock',20)?><span><strong><?=$overdue?> overdue returns</strong> across the fleet</span></div></div>
