<?php
try{
$r=isset($_GET['id'])?personnel_booking((int)$_GET['id']):null;
if($page==='personnel-create'){
 if($r&&((int)$r['requester_id']!==(int)$user['id']||!in_array($r['status'],['Draft','Returned for Correction'])))throw new RuntimeException('Only your drafts and returned requisitions can be edited.');
 $old=$_SESSION['old_input']??[];if(($old['action']??'')==='personnel_save'&&(int)($old['id']??0)===(int)($r['id']??0)){$r=array_replace($r??[],$old);unset($_SESSION['old_input']);}
 page_heading($r?'Edit personnel requisition':'New personnel requisition','Request a staff member for an official assignment.');
?><section class="panel form-panel"><form method="post" action="actions.php" class="form-body stack"><?=csrf()?><input type="hidden" name="action" value="personnel_save"><input type="hidden" name="id" value="<?=e($r['id']??0)?>"><input type="hidden" name="return_to" value="index.php?page=personnel-create<?=empty($r['id'])?'':'&id='.(int)$r['id']?>"><div class="form-grid"><label class="span-2">Required position / specialty<input name="requested_role" maxlength="160" required placeholder="For example: IT technician or administrative staff" value="<?=e($r['requested_role']??'')?>"></label><label class="span-2">Preferred personnel (optional)<input name="preferred_personnel" maxlength="160" placeholder="Enter the name of your preferred staff member" value="<?=e($r['preferred_personnel']??'')?>"><span class="field-hint">Subject to availability and administrator approval.</span></label><label>Start date &amp; time<input type="datetime-local" name="start_datetime" required value="<?=e(isset($r['start_datetime'])?date('Y-m-d\TH:i',strtotime($r['start_datetime'])):'')?>"></label><label>End date &amp; time<input type="datetime-local" name="end_datetime" required value="<?=e(isset($r['end_datetime'])?date('Y-m-d\TH:i',strtotime($r['end_datetime'])):'')?>"></label><?php $destinationSuggestions=false;require __DIR__.'/destination-fields.php';?><label class="span-2">Purpose / duties<textarea name="purpose" maxlength="5000" rows="4" required><?=e($r['purpose']??'')?></textarea></label></div><p class="field-hint">The administrator reviews your request and assigns available personnel for the requested schedule.</p><div class="form-actions"><a class="btn" href="index.php?page=personnel-bookings">Back to requisitions</a><button class="btn" name="submit_mode" value="draft">Save as draft</button><button class="btn primary" name="submit_mode" value="submit">Submit requisition</button></div></form></section><?php
 return;
}
if($page==='personnel-request'){
 if(!$r)throw new RuntimeException('Personnel requisition not found.');
 page_heading($r['reference'],'Personnel requisition','<a class="btn" href="index.php?page=personnel-bookings">Back to requisitions</a>'.(in_array($r['status'],['Approved','In Progress','Completed'])?'<a class="btn" href="print/personnel.php?id='.e(record_link_token((int)$r['id'],'personnel-print:id')).'">Print requisition</a>':''));
?><div class="detail-layout"><div><section class="panel"><div class="panel-heading"><h2>Assignment details</h2><?=badge($r['status'])?></div><dl class="detail-grid"><?php foreach(['Requested by'=>$r['requester_name'],'Office'=>$r['office_name'],'Required position / specialty'=>$r['requested_role'],'Preferred personnel'=>$r['preferred_personnel']?:'No preference','Assigned personnel'=>$r['personnel_name']??'Awaiting assignment','Start'=>shortdate($r['start_datetime'],'M j, Y g:i A'),'End'=>shortdate($r['end_datetime'],'M j, Y g:i A'),'Location'=>$r['destination'],'Purpose / duties'=>$r['purpose'],'Actual start'=>$r['actual_start']?shortdate($r['actual_start'],'M j, Y g:i A'):'—','Actual completion'=>$r['actual_end']?shortdate($r['actual_end'],'M j, Y g:i A'):'—'] as $label=>$value):?><div><dt><?=e($label)?></dt><dd><?=nl2br(e($value))?></dd></div><?php endforeach?></dl></section><section class="panel"><div class="panel-heading"><h2>Requisition history</h2></div><div class="form-body stack"><?php $history=all('SELECT h.*,u.full_name FROM personnel_booking_history h JOIN users u ON u.id=h.user_id WHERE booking_id=? ORDER BY h.id',[$r['id']]);foreach($history as $entry):?><div><strong><?=e($entry['decision'])?></strong><p><?=e($entry['full_name'])?> · <?=shortdate($entry['created_at'],'M j, Y g:i A')?></p><p><?=e($entry['remarks'])?></p></div><?php endforeach;if(!$history):?><p class="muted">No decisions recorded yet.</p><?php endif?></div></section></div><aside class="stack">
<?php if(is_role('Administrator')&&$r['status']==='Pending Administrative Approval'):?><section class="panel"><div class="panel-heading"><h2>Assign &amp; approve personnel</h2></div><form method="post" action="actions.php" class="form-body stack"><?=csrf()?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="return_to" value="index.php?page=personnel-request&id=<?=$r['id']?>"><div data-personnel-selections class="stack"><div class="personnel-selection-row"><label>Assign personnel<select name="personnel_ids[]" data-personnel-assignment="<?=$r['id']?>"><option value="">Select personnel</option><?php $staff=all('SELECT * FROM personnel ORDER BY full_name');$available=0;foreach($staff as $person):$issues=personnel_issues($person,$r);if(!$issues)$available++;?><option value="<?=$person['id']?>" <?=$issues?'disabled':''?>><?=e($person['full_name'].' · '.$person['classification'].' · '.$person['position'].' — '.($issues?implode(' ',$issues):'Available'))?></option><?php endforeach?></select></label><button class="btn small" type="button" data-personnel-remove hidden>Remove</button></div></div><button class="btn" type="button" data-personnel-add hidden>Add personnel</button><?php if(!$staff):?><p class="alert">No personnel have been added. <a href="index.php?page=personnel&add=1">Add personnel</a> to assign this requisition.</p><?php elseif(!$available):?><p class="alert">No personnel are available for this schedule.</p><?php endif?><p class="field-hint">Availability includes the <?=e(setting('turnaround_minutes','30'))?> minute turnaround buffer and is checked again when you approve.</p><button class="btn" type="button" data-personnel-check>Check availability</button><p data-personnel-result role="status" aria-live="polite">Select personnel to check availability.</p><label>Remarks<textarea name="remarks" rows="3" maxlength="2000" placeholder="Required when returning or rejecting"></textarea></label><label>Confirm with your password<input type="password" name="password" required autocomplete="current-password"></label><button class="btn primary" data-personnel-approve name="action" value="personnel_approve" <?=$available?'':'disabled'?>>Approve requisition</button><button class="btn" name="action" value="personnel_return">Return for correction</button><button class="btn danger" name="action" value="personnel_reject">Reject requisition</button></form></section><?php endif?>
<?php if((int)$r['requester_id']===(int)$user['id']&&in_array($r['status'],['Draft','Returned for Correction','Pending Administrative Approval','Approved'])):?><section class="panel"><div class="form-body stack"><?php if(in_array($r['status'],['Draft','Returned for Correction'])):?><a class="btn primary" href="<?=e(secure_record_url('index.php?page=personnel-create&id='.$r['id']))?>">Edit requisition</a><?php endif?><form action="actions.php" method="post" data-confirm="Cancel this personnel requisition?"><?=csrf()?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="return_to" value="index.php?page=personnel-request&id=<?=$r['id']?>"><button class="btn danger" name="action" value="personnel_cancel">Cancel requisition</button></form></div></section><?php endif?>
<?php if(is_role('Administrator','Dispatcher')&&in_array($r['status'],['Approved','In Progress','Completed']))require __DIR__.'/personnel-progress.php';?><?php if(deletion_allowed('personnel_bookings',$r)&&deletion_problem('personnel_bookings',$r)===''):?><section class="panel"><div class="form-body"><?=delete_link('personnel_bookings',$r)?></div></section><?php endif?></aside></div><script src="assets/js/personnel-assignment.js?v=<?=filemtime(__DIR__.'/../assets/js/personnel-assignment.js')?>" defer></script><?php
 return;
}
page_heading('Personnel requisitions','Request, approve, and track personnel assignments.','<a class="btn primary" href="index.php?page=personnel-create">'.icon('plus',17).' New personnel requisition</a>');
$date=is_string($_GET['date']??null)?$_GET['date']:'';
if($date!==''&&(!($parsed=DateTime::createFromFormat('!Y-m-d',$date))||$parsed->format('Y-m-d')!==$date))throw new RuntimeException('Enter a valid schedule date.');
$status=is_string($_GET['status']??null)?$_GET['status']:'';$q=is_string($_GET['q']??null)?trim($_GET['q']):'';
$rows=array_values(array_filter(personnel_bookings(),fn($b)=>($date===''||(substr($b['start_datetime'],0,10)<=$date&&substr($b['end_datetime'],0,10)>=$date))&&($status===''||$b['status']===$status)&&($q===''||stripos(implode(' ',[$b['reference'],$b['requested_role'],$b['destination'],$b['personnel_name']??'',$b['preferred_personnel'],$b['requester_name']]),$q)!==false)));
?><section class="panel"><form class="filter-bar" method="get"><input type="hidden" name="page" value="personnel-bookings"><input name="q" value="<?=e($q)?>" placeholder="Search requisitions or personnel" aria-label="Search personnel requisitions"><input type="date" name="date" value="<?=e($date)?>" aria-label="Assignment date"><select name="status" aria-label="Requisition status"><option value="">All statuses</option><?php foreach(['Draft','Pending Administrative Approval','Returned for Correction','Approved','In Progress','Completed','Rejected','Cancelled'] as $option):?><option <?=$status===$option?'selected':''?>><?=e($option)?></option><?php endforeach?></select><button class="btn">Filter</button></form><div class="table-scroll"><table class="data-table"><thead><tr><th>REQUISITION / LOCATION</th><th>REQUESTER</th><th>SCHEDULE</th><th>PERSONNEL</th><th>STATUS</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $b):?><tr><td><a class="table-title" href="<?=e(secure_record_url('index.php?page=personnel-request&id='.$b['id']))?>"><?=e($b['reference'])?></a><small><?=nl2br(e($b['destination']))?></small></td><td><?=e($b['requester_name'])?><small><?=e($b['office_name'])?></small></td><td><?=shortdate($b['start_datetime'],'M j, Y g:i A')?><small>to <?=shortdate($b['end_datetime'],'M j, Y g:i A')?></small></td><td><?=e($b['personnel_name']??'Awaiting assignment')?><small><?=e($b['requested_role'])?></small></td><td><?=badge($b['status'])?></td><td><div class="personnel-list-actions"><a class="btn small primary" href="<?=e(secure_record_url('index.php?page=personnel-request&id='.$b['id']))?>" aria-label="View personnel requisition <?=e($b['reference'])?>">View</a><?=delete_link('personnel_bookings',$b)?></div></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="6"><div class="empty-state"><h3>No personnel requisitions found</h3><p>Create a requisition or adjust your filters.</p></div></td></tr><?php endif?></tbody></table></div></section><?php
}catch(RuntimeException $e){echo '<div class="alert error">'.e($e->getMessage()).'</div>';}
