<?php
$schema=record_schemas()[$page];$editing=isset($_GET['edit']);$adding=isset($_GET['add']);$record=$editing?one("SELECT * FROM $page WHERE id=?",[(int)$_GET['edit']]):[];
page_heading($schema['title'],$schema['description'],'<a class="btn primary" href="index.php?page='.$page.'&add=1">'.icon('plus',17).' Add '.$schema['singular'].'</a>');
if($page==='users'&&!$editing&&!$adding)require __DIR__.'/registration-requests.php';
if($editing||$adding):
if($editing&&!$record){echo '<div class="alert error">Record not found.</div>';return;}
$old=$_SESSION['old_input']??[];unset($_SESSION['old_input']);if(($old['entity']??'')===$page)$record=array_replace($record??[],$old);
?><section class="panel form-panel"><div class="panel-heading"><h2><?=$editing?'Edit':'Add'?> <?=e($schema['singular'])?></h2><a href="index.php?page=<?=$page?>" class="text-link">Back to list</a></div><form method="post" action="actions.php" enctype="multipart/form-data" class="form-body"><?=csrf()?><input type="hidden" name="action" value="save_record"><input type="hidden" name="entity" value="<?=$page?>"><input type="hidden" name="id" value="<?=e($record['id']??'')?>"><input type="hidden" name="return_to" value="index.php?page=<?=$page?>&<?=$editing?'edit='.(int)$record['id']:'add=1'?>"><div class="form-grid"><?php foreach($schema['fields'] as $key=>$f):?><label><?=e($f['label'])?><?php if(isset($f['options'])):?><select name="<?=$key?>" required><?php foreach($f['options'] as $value=>$label):?><option value="<?=e($value)?>" <?=($record[$key]??'')==$value?'selected':''?>><?=e($label)?></option><?php endforeach?></select><?php else:?><input type="<?=e($f['type']??'text')?>" name="<?=$key?>" value="<?=e($key==='password'?'':($record[$key]??''))?>" <?=($f['optional']??false)?'':'required'?> <?=($f['type']??'')==='number'?'min="'.($f['min']??0).'"':''?> <?=($f['type']??'')==='password'?'autocomplete="new-password" minlength="12"':'maxlength="255"'?>><?php endif?></label><?php endforeach?><?php if($page==='users'):?><label>Confirm your administrator password<input type="password" name="confirmation_password" required autocomplete="current-password"></label><?php endif?><?php if($page==='vehicles'):?><label>Vehicle photograph <span class="field-hint">Optional JPEG or PNG, up to 4 MB</span><input type="file" name="photo" accept="image/jpeg,image/png"></label><?php endif?></div><div class="form-actions"><a class="btn" href="index.php?page=<?=$page?>">Cancel</a><button class="btn primary">Save <?=e($schema['singular'])?></button></div></form></section><?php return;endif;
$q=trim((string)($_GET['q']??''));$records=all("SELECT * FROM $page ORDER BY id DESC");if($q)$records=array_values(array_filter($records,fn($r)=>stripos(implode(' ',array_diff_key($r,['password_hash'=>true])),$q)!==false));
?><section class="panel"><form class="filter-bar"><input type="hidden" name="page" value="<?=$page?>"><div class="search-field"><?=icon('search',18)?><input name="q" value="<?=e($q)?>" aria-label="Search <?=e($schema['title'])?>" placeholder="Search <?=strtolower(e($schema['title']))?>…"></div><button class="btn">Search</button></form>
<?php if($page==='vehicles'):?><div class="vehicle-grid"><?php foreach($records as $v):$inUse=one("SELECT id FROM requisitions WHERE vehicle_id=? AND status='Dispatched'",[$v['id']]);$blocked=one('SELECT id FROM vehicle_blocks WHERE vehicle_id=? AND start_datetime<=? AND end_datetime>?',[$v['id'],date('Y-m-d H:i:s'),date('Y-m-d H:i:s')]);$reserved=one("SELECT id FROM requisitions WHERE vehicle_id=? AND status='Approved' AND start_datetime<=? AND end_datetime>?",[$v['id'],date('Y-m-d H:i:s'),date('Y-m-d H:i:s')]);?><article class="vehicle-card"><div class="vehicle-illustration <?=strtolower($v['type'])?>"><?php if(!empty($v['photo_url'])):?><img src="<?=e($v['photo_url'])?>" alt="<?=e($v['model'])?>"><?php else:?><?=icon('car',85)?><?php endif?><span><?=e($v['type'])?></span></div><div class="vehicle-card-body"><div class="vehicle-name"><h3><?=e($v['model'])?></h3><?=badge($inUse?'In Use':($blocked?'Under Maintenance':($reserved?'Reserved':$v['status'])))?></div><span class="plate"><?=e($v['plate'])?></span><div class="vehicle-specs"><span><?=icon('users',16)?> <?=$v['capacity']?> seats</span><span><?=number_format($v['odometer'])?> km</span></div><a class="btn primary vehicle-edit-button" href="<?=e(secure_record_url('index.php?page=vehicles&edit='.$v['id']))?>" aria-label="Edit <?=e($v['model'].' · '.$v['plate'])?>">Edit vehicle</a></div></article><?php endforeach?></div><?php else:?><div class="table-scroll"><table class="data-table"><thead><tr><?php foreach($schema['fields'] as $key=>$f)if(!in_array($key,['password','position','license_number']))echo '<th>'.e($f['label']).'</th>';?><th></th></tr></thead><tbody><?php foreach($records as $r):?><tr><?php foreach($schema['fields'] as $key=>$f){if(in_array($key,['password','position','license_number']))continue;?><td><?=$key==='status'?badge($r[$key]):e($f['options'][$r[$key]]??$r[$key])?></td><?php }?><td><a class="text-link" href="<?=e(secure_record_url('index.php?page='.$page.'&edit='.$r['id']))?>">Edit</a></td></tr><?php endforeach?></tbody></table></div><?php endif;if(!$records):?><div class="empty-state"><h3>No records found</h3><p>Add a record or adjust your search.</p></div><?php endif?><div class="table-footer"><?=count($records)?> <?=strtolower(e($schema['title']))?></div></section>
