<?php
require_once __DIR__.'/work-reminders.php';
$work=work_reminders($rows,$personnelRows,$now,(int)$user['id']);
$carried=count(array_filter($work,fn($r)=>$r['carryover']));
$accountCount=is_role('Administrator')?(int)one("SELECT COUNT(*) n FROM users WHERE status='Pending'")['n']:0;
?>
<section class="panel work-reminders" aria-labelledby="work-reminders-title"><div class="panel-heading"><div><h2 id="work-reminders-title">Today’s work &amp; unfinished items <span class="count-pill"><?=count($work)+$accountCount?></span></h2><p>Due today and still open from earlier days. Unfinished items stay here until resolved.</p></div><span class="work-day"><?=icon('calendar',16)?> <?=date('M j, Y')?></span></div>
<div class="work-summary"><span><strong><?=count($work)?></strong> open requisitions</span><span class="<?=$carried?'work-warning':''?>"><strong><?=$carried?></strong> carried over</span><span><?=e($config['timezone'])?></span></div>
<?php if($accountCount):?><a class="work-account" href="index.php?page=account-requests"><?=icon('shield',19)?><span><strong><?=$accountCount?> account request<?=$accountCount===1?'':'s'?> awaiting approval</strong><small>Review who can access the workspace.</small></span><?=icon('chevron',18)?></a><?php endif?>
<div class="work-list"><?php foreach($work as $item):$personnel=$item['request_kind']==='Personnel';$detail=secure_record_url('index.php?page='.($personnel?'personnel-request':'request').'&id='.$item['id']);?>
<article class="work-item <?=$item['overdue']?'is-overdue':''?>"><span class="work-icon" aria-hidden="true"><?=icon($personnel?'users':'car',21)?></span><div class="work-copy"><div class="work-meta"><span><?=e($item['request_kind'])?></span><?php if($item['carryover']):?><span class="work-warning">Carried over · <?=shortdate($item['start_datetime'],'M j')?></span><?php endif?><?php if($item['overdue']):?><span class="work-warning">Past scheduled end</span><?php endif?></div><h3><a href="<?=e($detail)?>"><?=e($item['reference'])?> · <?=e($item['reminder_task'])?></a></h3><p><?=nl2br(e($item['destination']))?></p><div class="work-meta"><span><?=e($item['requester_name'])?> · <?=e($item['office_code'])?></span><span><?=e($personnel?($item['personnel_name']??'Personnel not assigned'):($item['model']??'Vehicle not assigned'))?></span></div><div class="work-schedule"><span>Start <strong><?=shortdate($item['start_datetime'],'M j, Y · g:i A')?></strong></span><span>End <strong><?=shortdate($item['end_datetime'],'M j, Y · g:i A')?></strong></span></div><?php if($item['status']==='Approved'&&$item['overdue']):?><p class="work-warning">The schedule has ended. Review this request to resolve or reschedule it.</p><?php endif?></div><div class="work-actions"><?=badge($item['status'])?><a class="btn small primary" href="<?=e($detail)?>" aria-label="Open <?=e($item['reference'])?>">Open request <?=icon('chevron',14)?></a></div></article>
<?php endforeach;if(!$work&&!$accountCount):?><div class="empty-state"><?=icon('check',30)?><h3>You’re up to date</h3><p>No unfinished work is due today. Upcoming requests will appear on their scheduled day.</p></div><?php endif?></div></section>
